### ISSUE TITLE
feat: Charger le fichier de configuration depuis un fichier YAML

### ISSUE THREAD

**Issue by stephrobert** [stephrobert/ImageValidator#2]
Le fichier de configuration est dans le répertoire courant et pour le moment ressemble à ceci

```yaml
# Configuration générale pour la validation des images de VM
tests:
  - name: "Vérification des services"
    type: "service_check"
    services: ["ssh", "cloud-init"]

  - name: "Vérification des drivers"
    type: "driver_check"
    drivers: ["virtio"]

  - name: "Validation du boot GRUB"
    type: "boot_check"
    boot_params: ["console=ttyS0"]

# Configuration de logging
logging:
  level: "INFO"  # Niveau de log : DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(levelname)s - %(message)s"  # Format des messages de log
  file: "/var/log/image_validator.log"  # Chemin du fichier de log (peut être configuré)

# Configuration du cloud cible
target_cloud:
  provider: "Outscale"  # Nom du cloud cible, par ex. : AWS, Azure, GCP, OpenStack
  options:
    # Exemples d'options spécifiques au cloud
    region: "eu-west-2"
    instance_type: "tinav5.c1r2p3"
    ssh_user: "outscale"  # Nom d'utilisateur par défaut pour SSH
```
